### ISSUE TITLE
[ Feature ] 대학교 요소 추가

### ISSUE THREAD

**Issue by tjrmswo** [FRONTLINE2024/bamboo_skj#33]
## 배경
이게 왜 필요한지에 대한 설명.
예를 들어서 기능 구현의 경우 어떤 라이브러를 썼을 때 
무지성 도입이 아니라 왜 이걸 썼는지에 대한 설명
기능 수정은 왜 수정해야하는지 등등

찬찬히 생각해보니 대학교 커뮤니티인데 대학교 요소가 하나도 없어서 추가하려고 함
수도권 대학만 일단 select 태그를 통해 선택할 수 있게 하고 거기에 없다면 직접 입력해서 DB에 넣는 방식으로 진행

## ✅ TODO
- [ ] DB에 대학교 컬럼 생성
- [ ] 대학교 value 추가하는 로직 추가
- [ ] 대학교 반환값 추가 및 UI 요소 추가
