### ISSUE TITLE
[ Feature ] 반응형 적용

### ISSUE THREAD

**Issue by tjrmswo** [FRONTLINE2024/bamboo_skj#42]
## 배경
사용자의 디바이스 종류와 화면 크기에 관계없이 최적화된 사용자 경험을 제공하기 위해 전체 UI를 반응형으로 적용함으로써 모바일과 테블릿 웹이 모두 호환될 수 있게 구성

## ✅ TODO
- [x] 로그인 페이지 반응형 적용
- [x] 회원가입 페이지 반응형 적용
- [x] 홈페이지 반응형 적용
